#!/bin/sh
# /etc/init.d/power-monitor

case "$1" in
	start)
		echo "Starting power monitor..."
		echo 4 > /sys/class/gpio/export
		echo falling > /sys/class/gpio/gpio4/edge
		gpio-irq 4 &
		;;
	stop)
		echo "Stopping power monitor..."
		killall gpio-irq
		;;
	*)
		echo "Usage: /etc/init.d/power-monitor (start|stop)"
		exit 1
		;;
esac

exit 0
